/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.triinfotech.gui;

import in.triinfotech.entity.EyeSight;
import in.triinfotech.entity.controller.EyeSightJpaController;
import in.triinfotech.utilities.DateConverter;
import in.triinfotech.utilities.Helper;

/**
 *
 * @author ajay
 */
public class EyeSightTest extends javax.swing.JFrame {
    
    private EyeSightJpaController eyeSightController;
    
    /**
     * Creates new form EyeSightTest
     */
    public EyeSightTest() {
        initComponents();
        
        getRootPane().setDefaultButton(btnSave);
        
        eyeSightController = Helper.getEyeSightControllerInstance();
        Helper.centerScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        LovelyOpticalsPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("LovelyOpticalsPU").createEntityManager();
        customerQuery = java.beans.Beans.isDesignTime() ? null : LovelyOpticalsPUEntityManager.createQuery("SELECT c FROM Customer c");
        customerList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : customerQuery.getResultList();
        pnlCustomer = new javax.swing.JPanel();
        cmbCustomer = new javax.swing.JComboBox<>();
        lblCustomer = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblPinCode = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtPincode = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        pnlEyeSight = new javax.swing.JPanel();
        lblLeft = new javax.swing.JLabel();
        lblSph = new javax.swing.JLabel();
        lblCyl = new javax.swing.JLabel();
        lblAxis = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        txtSphLeft = new javax.swing.JTextField();
        txtCylLeft = new javax.swing.JTextField();
        txtAxisLeft = new javax.swing.JTextField();
        txtAddLeft = new javax.swing.JTextField();
        txtSphRight = new javax.swing.JTextField();
        txtCylRight = new javax.swing.JTextField();
        txtAxisRight = new javax.swing.JTextField();
        txtAddRight = new javax.swing.JTextField();
        lblRight = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setTitle("Eye Sight Testing");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Information"));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, customerQuery, eLProperty, cmbCustomer);
        bindingGroup.addBinding(jComboBoxBinding);

        lblCustomer.setText("Customer:");

        lblCity.setText("City:");

        lblPinCode.setText("Pin Code:");

        lblState.setText("State:");

        lblEmail.setText("Email:");

        lblContact.setText("Contact:");

        lblDateOfBirth.setText("Date of Birth:");

        txtCity.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cmbCustomer, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.city}"), txtCity, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtPincode.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cmbCustomer, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.pinCode}"), txtPincode, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtEmail.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cmbCustomer, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.phoneNumber}"), txtEmail, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtContact.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cmbCustomer, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.email}"), txtContact, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtDateOfBirth.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cmbCustomer, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.dateOfBirth}"), txtDateOfBirth, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(new DateConverter());
        bindingGroup.addBinding(binding);

        txtState.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cmbCustomer, org.jdesktop.beansbinding.ELProperty.create("${selectedItem.state}"), txtState, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnlCustomerLayout = new javax.swing.GroupLayout(pnlCustomer);
        pnlCustomer.setLayout(pnlCustomerLayout);
        pnlCustomerLayout.setHorizontalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomerLayout.createSequentialGroup()
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCustomerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateOfBirth)
                            .addComponent(lblCustomer)))
                    .addGroup(pnlCustomerLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCity)
                            .addComponent(lblPinCode)
                            .addComponent(lblState)
                            .addComponent(lblEmail)
                            .addComponent(lblContact))))
                .addGap(19, 19, 19)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlCustomerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbCustomer, txtCity, txtContact, txtDateOfBirth, txtEmail, txtPincode, txtState});

        pnlCustomerLayout.setVerticalGroup(
            pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomer)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPinCode)
                    .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCustomerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbCustomer, txtCity, txtContact, txtDateOfBirth, txtEmail, txtPincode, txtState});

        pnlEyeSight.setBorder(javax.swing.BorderFactory.createTitledBorder("Eye Sight"));

        lblLeft.setText("Left Eye");

        lblSph.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSph.setText("SPH");

        lblCyl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCyl.setText("CYL");

        lblAxis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAxis.setText("AXIS");

        lblAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdd.setText("ADD");

        txtSphLeft.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txtCylLeft.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txtAxisLeft.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txtAddLeft.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txtSphRight.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txtCylRight.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txtAxisRight.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        txtAddRight.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        lblRight.setText("Right Eye");

        javax.swing.GroupLayout pnlEyeSightLayout = new javax.swing.GroupLayout(pnlEyeSight);
        pnlEyeSight.setLayout(pnlEyeSightLayout);
        pnlEyeSightLayout.setHorizontalGroup(
            pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEyeSightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRight)
                    .addComponent(lblLeft))
                .addGap(26, 26, 26)
                .addGroup(pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSph, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSphLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSphRight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCyl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(txtCylLeft, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCylRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAxis, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(txtAxisLeft)
                    .addComponent(txtAxisRight, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(txtAddLeft, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAddRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlEyeSightLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAdd, lblAxis, lblCyl, lblSph, txtAddLeft, txtAddRight, txtAxisLeft, txtAxisRight, txtCylLeft, txtCylRight, txtSphLeft, txtSphRight});

        pnlEyeSightLayout.setVerticalGroup(
            pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEyeSightLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAxis, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSph)
                        .addComponent(lblCyl)
                        .addComponent(lblAdd)))
                .addGap(18, 18, 18)
                .addGroup(pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSphLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCylLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAxisLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeft))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEyeSightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSphRight, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCylRight, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAxisRight, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddRight, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRight))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlButtons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCancel.setMnemonic('c');
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setMnemonic('s');
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap())
        );

        pnlButtonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnSave});

        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEyeSight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlEyeSight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close() {
        setVisible(false);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        close();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close();
    }//GEN-LAST:event_formWindowClosing

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtAddLeft.getText().isEmpty()) {
            txtAddLeft.setText("0.0");
        }
        
        if (txtAddRight.getText().isEmpty()) {
            txtAddRight.setText("0.0");
        }
        
        if (txtAxisLeft.getText().isEmpty()) {
            txtAxisLeft.setText("0.0");
        }
        
        if (txtAxisRight.getText().isEmpty()) {
            txtAxisRight.setText("0.0");
        }
        
        if (txtCylLeft.getText().isEmpty()) {
            txtCylLeft.setText("0.0");
        }
        
        if (txtCylRight.getText().isEmpty()) {
            txtCylRight.setText("0.0");
        }
        
        if (txtSphLeft.getText().isEmpty()) {
            txtSphLeft.setText("0.0");
        }
        
        if (txtSphRight.getText().isEmpty()) {
            txtSphRight.setText("0.0");
        }
        
        EyeSight eyeSight = new EyeSight();
        eyeSight.setAddLeftEye(Float.parseFloat(txtAddLeft.getText().trim()));
        eyeSight.setAddRightEye(Float.parseFloat(txtAddRight.getText().trim()));
        eyeSight.setAxisLeftEye(Float.parseFloat(txtAxisLeft.getText().trim()));
        eyeSight.setAxisRightEye(Float.parseFloat(txtAxisRight.getText().trim()));
        eyeSight.setCylLeftEye(Float.parseFloat(txtCylLeft.getText().trim()));
        eyeSight.setCylRightEye(Float.parseFloat(txtCylRight.getText().trim()));
        eyeSight.setSphLeftEye(Float.parseFloat(txtSphLeft.getText().trim()));
        eyeSight.setSphRightEye(Float.parseFloat(txtSphRight.getText().trim()));
        eyeSight.setCustomer((in.triinfotech.entity.Customer) cmbCustomer.getSelectedItem());
        eyeSightController.create(eyeSight);
        
        Helper.showSuccessMessage(this, "Record Added Successfully!");
        
        close();
    }//GEN-LAST:event_btnSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager LovelyOpticalsPUEntityManager;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbCustomer;
    private java.util.List<in.triinfotech.entity.Customer> customerList;
    private javax.persistence.Query customerQuery;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblAxis;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblCyl;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblPinCode;
    private javax.swing.JLabel lblRight;
    private javax.swing.JLabel lblSph;
    private javax.swing.JLabel lblState;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCustomer;
    private javax.swing.JPanel pnlEyeSight;
    private javax.swing.JTextField txtAddLeft;
    private javax.swing.JTextField txtAddRight;
    private javax.swing.JTextField txtAxisLeft;
    private javax.swing.JTextField txtAxisRight;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtCylLeft;
    private javax.swing.JTextField txtCylRight;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPincode;
    private javax.swing.JTextField txtSphLeft;
    private javax.swing.JTextField txtSphRight;
    private javax.swing.JTextField txtState;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
